# Generated by Django 4.2.25 on 2025-10-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        help_text="Email para o qual a notificação será enviada",
                        max_length=254,
                        verbose_name="Email do Destinatário",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Assunto do email",
                        max_length=200,
                        verbose_name="Assunto",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Corpo da mensagem do email", verbose_name="Mensagem"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("sent", "Enviado"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes do erro, caso o envio falhe",
                        null=True,
                        verbose_name="Mensagem de Erro",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Envio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-created_at"],
            },
        ),
    ]
