# Generated by Django 4.2.25 on 2025-10-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_email', 'subject', 'message', 'status'], name='notif_dup_check_idx'),
        ),
    ]
